<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5a4e3c8ce5cf2',
    'title' => __('Rss Feeds', 'modularity-testimonials'),
    'fields' => array(
        0 => array(
            'key' => 'field_5a4f4f70314d0',
            'label' => __('General', 'modularity-testimonials'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        1 => array(
            'key' => 'field_5a4e3c9a10aa7',
            'label' => __('Add rss feeds', 'modularity-testimonials'),
            'name' => 'mod_rss',
            'type' => 'repeater',
            'instructions' => __('Add one or more rss-feeds to display them', 'modularity-testimonials'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => '',
            'min' => 1,
            'max' => 10,
            'layout' => 'table',
            'button_label' => __('Add feed', 'modularity-testimonials'),
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_5a4f4f0fcf9cc',
                    'label' => __('Rss label', 'modularity-testimonials'),
                    'name' => 'mod_rss_label',
                    'type' => 'text',
                    'instructions' => __('Name this feed, if its empty the feed name will be used (if active in display settings).', 'modularity-testimonials'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                1 => array(
                    'key' => 'field_5a4e3ca510aa8',
                    'label' => __('Rss Url', 'modularity-testimonials'),
                    'name' => 'mod_rss_url',
                    'type' => 'url',
                    'instructions' => __('Enter a valid rss-feed', 'modularity-testimonials'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_5a4f4f84314d1',
            'label' => __('Display settings', 'modularity-testimonials'),
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        3 => array(
            'key' => 'field_5a4f3861781a9',
            'label' => __('Limit to max number of inlays', 'modularity-testimonials'),
            'name' => 'mod_rss_limit',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 7,
            'placeholder' => __('Enter a number for max limit', 'modularity-testimonials'),
            'prepend' => '',
            'append' => __('number of inlays', 'modularity-testimonials'),
            'min' => 1,
            'max' => 20,
            'step' => 1,
        ),
        4 => array(
            'key' => 'field_5a4f4f8e314d2',
            'label' => __('Display parts', 'modularity-testimonials'),
            'name' => 'mod_rss_display',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'label' => __('Show label', 'modularity-testimonials'),
                'excerpt' => __('Show excerpt', 'modularity-testimonials'),
                'date' => __('Show date', 'modularity-testimonials'),
                'readmore' => __('Show read more', 'modularity-testimonials'),
                'content' => __('Show full content', 'modularity-testimonials'),
            ),
            'allow_custom' => 0,
            'save_custom' => 0,
            'default_value' => array(
                0 => 'label',
                1 => 'excerpt',
                2 => 'date',
            ),
            'layout' => 'horizontal',
            'toggle' => 0,
            'return_format' => 'value',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-rssfeed',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}